server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
